### ISSUE TITLE
Вопрос по курсу

### ISSUE THREAD

**Issue by shulgin-egor** [CompMathGroup/NumMethods#1]
Здравствуйте, Иван.
Вы не могли рассказать о формате данного курса? Он является курсом по выбору? Можно ли его посещать другим студентам и когда он проходит?

**Comment by uranix** [comment]
Здравствуйте, курс проходит в 9:00 по вторникам в аудитории 801 КПМ. Курс является базовым для группы «Science Engineering: Моделирование нефтегазовых месторождений», но в аудитории хватит места для еще нескольких желающих. Не знаю, можно ли курс засчитать как КПВ, это вам лучше узнать в учебном отделе. Формат - практические занятия + домашние задания на программирование численных методов.
